name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository Pull
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: application.properties 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: 빌드 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./outify.jar

      - name: 압축
        run: tar -czvf $GITHUB_SHA.tar.gz outify.jar appspec.yml scripts

      - name: AWS Resource 접근을 위한 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 프로젝트 폴더 S3에 업로드
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://server/$GITHUB_SHA.tar.gz

      - name: EC2 인스턴스에 프로젝트 코드 배포 명령 (Code Deploy)
        run: aws deploy create-deployment
            --application-name server
            --deployment-config-name CodeDeployDefault.AllAtOnce
            --deployment-group-name Production
            --s3-location bucket=server,bundleType=tgz,key=$GITHUB_SHA.tar.gz